name: pyperformance (Python nogil-3.9.10)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-image
    - name: Install
      run: docker run python-image make install
    - name: Run pyperformance
      run: docker run python-image python -m pyperformance -o nogil-3.9.10.json
    - name: Show pyperformance result
      run: cat nogil-3.9.10.json
